/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @see       http://buildwithcraft.com
 @package   craft.app.resources
*/
(function(c){Craft.RichTextInput=Garnish.Base.extend({id:null,sectionSources:null,elementLocale:null,redactorConfig:null,$textarea:null,redactor:null,init:function(b,f,a,e,d){this.id=b;this.sectionSources=f;this.elementLocale=a;this.redactorConfig=e;this.redactorConfig.lang=d;this.redactorConfig.direction=Craft.orientation;this.redactorConfig.imageUpload=!0;var g=this,h=e.initCallback;this.redactorConfig.initCallback=function(a,e){g.redactor=this;g.onRedactorInit();return c.isFunction(h)?h.call(this,
a,e):e};this.$textarea=c("#"+this.id);this.initRedactor();"undefined"!=typeof Craft.livePreview&&(Craft.livePreview.on("beforeEnter beforeExit",c.proxy(function(){this.redactor.core.destroy()},this)),Craft.livePreview.on("enter slideOut",c.proxy(function(){this.initRedactor()},this)))},initRedactor:function(){this.$textarea.redactor(this.redactorConfig);this.redactor=this.$textarea.data("redactor")},onRedactorInit:function(){this.redactor.opts.toolbar&&this.customizeToolbar();this.leaveFullscreetOnSaveShortcut()},
customizeToolbar:function(){var b=this.replaceRedactorButton("image",Craft.t("Insert image")),f=this.replaceRedactorButton("link",Craft.t("Link"));b&&this.redactor.button.addCallback(b,c.proxy(function(){this.redactor.selection.save();"undefined"==typeof this.assetSelectionModal?this.assetSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.ChooseImage",multiSelect:!0,criteria:{locale:this.elementLocale,kind:"image"},onSelect:c.proxy(function(a,e){if(a.length){this.redactor.selection.restore();
for(var d=0;d<a.length;d++){var b=a[d],b=b.url+"#asset:"+b.id;e&&(b+=":"+e);this.redactor.insert.node(c('<img src="'+b+'" />')[0]);this.redactor.code.sync()}this.redactor.observe.images();this.redactor.dropdown.hideAll()}},this),closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetSelectionModal.show()},this));f&&this.redactor.button.addDropdown(f,{link_entry:{title:Craft.t("Link to an entry"),func:c.proxy(function(){this.redactor.selection.save();"undefined"==typeof this.entrySelectionModal?
this.entrySelectionModal=Craft.createElementSelectorModal("Entry",{storageKey:"RichTextFieldType.LinkToEntry",sources:this.sectionSources,criteria:{locale:this.elementLocale},onSelect:c.proxy(function(a){if(a.length){this.redactor.selection.restore();a=a[0];var b=a.url+"#entry:"+a.id,d=this.redactor.selection.getText();this.redactor.insert.node(c('<a href="'+b+'">'+(0<d.length?d:a.label)+"</a>")[0]);this.redactor.code.sync()}this.redactor.dropdown.hideAll()},this),closeOtherModals:!1}):this.entrySelectionModal.show()},
this)},link_asset:{title:Craft.t("Link to an asset"),func:c.proxy(function(){this.redactor.selection.save();"undefined"==typeof this.assetLinkSelectionModal?this.assetLinkSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.LinkToAsset",criteria:{locale:this.elementLocale},onSelect:c.proxy(function(a){if(a.length){this.redactor.selection.restore();a=a[0];var b=a.url+"#asset:"+a.id,d=this.redactor.selection.getText();this.redactor.insert.node(c('<a href="'+b+'">'+
(0<d.length?d:a.label)+"</a>")[0]);this.redactor.code.sync()}this.redactor.dropdown.hideAll()},this),closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetLinkSelectionModal.show()},this)},link:{title:Craft.t("Insert link"),func:"link.show"},unlink:{title:Craft.t("Unlink"),func:"link.unlink"}})},leaveFullscreetOnSaveShortcut:function(){if("undefined"!=typeof this.redactor.fullscreen&&"function"==typeof this.redactor.fullscreen.disable)Craft.cp.on("beforeSaveShortcut",c.proxy(function(){this.redactor.fullscreen.isOpen&&
this.redactor.fullscreen.disable()},this))},replaceRedactorButton:function(b,c){if(this.redactor.button.get(b).length){var a=b+"_placeholder";this.redactor.button.addAfter(b,a);this.redactor.button.remove(b);var e=this.redactor.button.addAfter(a,b,c);this.redactor.button.remove(a);return e}}})})(jQuery);

//# sourceMappingURL=RichTextInput.min.map
