/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @see       http://buildwithcraft.com
 @package   craft.app.resources
*/
(function(b){Craft.UpdateInfo=Garnish.Base.extend({appUpdateInfo:null,$container:null,$downloadBtn:null,licenseHud:null,$licenseSubmitBtn:null,licenseSubmitAction:null,allowAutoUpdates:null,init:function(){var c=b("#graphic"),d=b("#status");Craft.postActionRequest("update/getAvailableUpdates",b.proxy(function(a,f){if("success"!=f||a.error||a.errors){var e=Craft.t("An unknown error occurred.");a.errors&&a.errors.length?e=a.errors[0]:a.error&&(e=a.error);c.addClass("error");d.text(e)}else e={total:a.app&&
a.app.releases&&a.app.releases.length?1:0,critical:a.app&&a.criticalUpdateAvailable},e.total?(c.velocity("fadeOut",{duration:"fast"}),d.fadeOut("fast",b.proxy(function(){c.remove();d.remove();this.appUpdateInfo=a.app;this.allowAutoUpdates=a.allowAutoUpdates;this.showAvailableUpdates()},this))):(c.addClass("success"),d.text(Craft.t("You\u2019re all up-to-date!"))),Craft.cp.displayUpdateInfo(e)},this))},showAvailableUpdates:function(){this.$container=b("<div/>").appendTo(Craft.cp.$main).hide();var c=
b('<div class="pane clearafter"/>').appendTo(this.$container);b('<h2 class="heading">'+Craft.t("You\u2019ve got updates!")+"</h2>").appendTo(c);var d=b('<div class="buttons"/>').appendTo(c);if(c=!this.allowAutoUpdates||this.appUpdateInfo.manualUpdateRequired)this.$downloadBtn=b('<div class="btn submit">'+Craft.t("Download")+"</div>").appendTo(d);else{var a=b('<div class="btngroup submit"/>').appendTo(d),f=b('<div class="btn submit">'+Craft.t("Update")+"</div>").appendTo(a),d=b('<div class="btn submit menubtn"/>').appendTo(a),
a=b('<div class="menu" data-align="right"/>').appendTo(a),a=b("<ul/>").appendTo(a),a=b("<li/>").appendTo(a);this.$downloadBtn=b("<a>"+Craft.t("Download")+"</a>").appendTo(a);new Garnish.MenuBtn(d)}this.appUpdateInfo.licenseUpdated?(this.addListener(this.$downloadBtn,"click","showLicenseForm"),c||this.addListener(f,"click","showLicenseForm")):(this.addListener(this.$downloadBtn,"click","downloadThat"),c||this.addListener(f,"click","autoUpdateThat"));this.showReleases(this.appUpdateInfo.releases,"Craft");
this.$container.velocity("fadeIn",{duration:"fast"})},showLicenseForm:function(c){c.stopPropagation();if(this.licenseHud)this.licenseHud.$trigger=b(c.currentTarget),this.licenseHud.show();else{var d=b("<form><p>"+Craft.t('Craft\u2019s <a href="http://buildwithcraft.com/license" target="_blank">Terms and Conditions</a> have changed.')+"</p></form>"),a=b("<label> "+Craft.t("I agree.")+" &nbsp;</label>").appendTo(d),f=b('<input type="checkbox"/>').prependTo(a);this.$licenseSubmitBtn=b('<input class="btn submit" type="submit"/>').appendTo(d);
this.licenseHud=new Garnish.HUD(c.currentTarget,d);this.addListener(d,"submit",function(a){a.preventDefault();f.prop("checked")?(this.licenseSubmitAction(),this.licenseHud.hide(),f.prop("checked",!1)):Garnish.shake(this.licenseHud.$hud)})}c.currentTarget==this.$downloadBtn[0]?(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, download.")),this.licenseSubmitAction=this.downloadThat):(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, update.")),this.licenseSubmitAction=this.autoUpdateThat)},
showReleases:function(c,d){for(var a=0;a<c.length;a++){var f=b('<div class="pane release"/>').appendTo(this.$container),e=c[a],g=d+" "+e.version;e.build&&(g+=' <span class="light">'+Craft.t("build {build}",{build:e.build})+"</span>");e.critical&&(g+=' <span class="critical">'+Craft.t("Critical")+"</span>");b("<h2>"+g+"</h2>").appendTo(f);b('<div class="notes"/>').appendTo(f).html(e.notes)}},downloadThat:function(){var c=this.appUpdateInfo.manualDownloadEndpoint;"https:"==window.location.protocol&&
(c=c.replace("http:","https:"));b("<iframe/>",{src:c}).appendTo(Garnish.$bod).hide()},autoUpdateThat:function(){window.location.href=Craft.getUrl("updates/go/craft")}})})(jQuery);

//# sourceMappingURL=updates.min.map
